services:
  ai-detector-web:
    build: .
    container_name: ai-detector-web
    ports:
      - "8000:8000"
    gpus: all
    env_file:
      - .env
    environment:
      HF_HOME: /root/.cache/huggingface
      HUGGINGFACE_HUB_CACHE: /root/.cache/huggingface/hub
      HF_HUB_DISABLE_XET: "1"
      HF_HUB_ENABLE_HF_TRANSFER: "0"
    volumes:
      - ./data:/app/data
      - ./hf-cache:/root/.cache/huggingface
      - ./models:/app/models
